#!/bin/sh
# Desabilitar output
exec >/dev/null 2>&1

#--- Papel de Parede ---
nitrogen --restore &

#--- Terminais ---#
#tilda &
guake &

#--- Compositores ---
#~/.compstart

#--- Daemons de notificação ---
#notipy &
#xfce4-notifyd &
#notification-daemon &

#--- Mensageiros ---
#skype &
pidgin &

#--- Controle de volume
#volwheel &
#volumeicon
#volti &
#pyvol &

#--- Gerenciadores de clipboard ---
loliclip &

#--- Torrent ---
# deluge &
#deluged &

#--- ... ---
fluxbox -log /home/laracraft304/.fluxbox.log
