#!/bin/bash
editor="${EDITOR:-vi}"                # PKGBUILD editor
editpkgbuild=false                    # edit PKGBUILD script
editinstall=false                     # edit install script
fallback=true                         # pacman fallback to the AUR
clean=true                            # clean up after package install
cleandevel=true                       # clean up devel package
color=true                            # color support via pacman-color
secure=false                          # enhanced security

