#!/bin/bash

yaourt --needed --noconfirm -S aewan
yaourt --needed --noconfirm -S alsaequal
yaourt --needed --noconfirm -S alsamixergui
yaourt --needed --noconfirm -S android-ndk
yaourt --needed --noconfirm -S android-sdk
yaourt --needed --noconfirm -S android-sdk-platform-tools
yaourt --needed --noconfirm -S arm-linux-gnueabi-binutils
yaourt --needed --noconfirm -S asciiquarium
yaourt --needed --noconfirm -S bash-game-manager
yaourt --needed --noconfirm -S cdspeed
yaourt --needed --noconfirm -S cinnamon
yaourt --needed --noconfirm -S compton-git
yaourt --needed --noconfirm -S cpuled
yaourt --needed --noconfirm -S downgrade
yaourt --needed --noconfirm -S e4rat-lite-git
yaourt --needed --noconfirm -S flrec
yaourt --needed --noconfirm -S fltk11
yaourt --needed --noconfirm -S fortune-mod-br
yaourt --needed --noconfirm -S freerapid
yaourt --needed --noconfirm -S freetype2-lcd
yaourt --needed --noconfirm -S fretscpp
yaourt --needed --noconfirm -S geany-git
yaourt --needed --noconfirm -S geany-plugins-git
yaourt --needed --noconfirm -S geany-themes-git
yaourt --needed --noconfirm -S glew1.5
yaourt --needed --noconfirm -S gmtp
yaourt --needed --noconfirm -S gnome-colors-icon-theme
yaourt --needed --noconfirm -S gnome-colors-icon-theme-extras
yaourt --needed --noconfirm -S grub
yaourt --needed --noconfirm -S gtk-rezlooks-engine
yaourt --needed --noconfirm -S gtkglarea
yaourt --needed --noconfirm -S gvolwheel
yaourt --needed --noconfirm -S iocane
yaourt --needed --noconfirm -S jd-gui
yaourt --needed --noconfirm -S jdk
yaourt --needed --noconfirm -S ksh
yaourt --needed --noconfirm -S lib32-alsaequal
yaourt --needed --noconfirm -S lib32-caps
yaourt --needed --noconfirm -S lib32-curl
yaourt --needed --noconfirm -S lib32-fuse
yaourt --needed --noconfirm -S lib32-glew1.5
yaourt --needed --noconfirm -S lib32-gtk-engine-murrine
yaourt --needed --noconfirm -S lib32-ladspa
yaourt --needed --noconfirm -S lib32-libjpeg6
yaourt --needed --noconfirm -S lib32-libusb
yaourt --needed --noconfirm -S lib32-libxxf86dga
yaourt --needed --noconfirm -S lib32-nvidia-utils-beta
yaourt --needed --noconfirm -S lib32-sdl_mixer
yaourt --needed --noconfirm -S lib32-smpeg
yaourt --needed --noconfirm -S libgksu-no-remember-pass
yaourt --needed --noconfirm -S libjpeg6
yaourt --needed --noconfirm -S libtiff3
yaourt --needed --noconfirm -S mingw-w64-binutils
yaourt --needed --noconfirm -S mingw-w64-headers
yaourt --needed --noconfirm -S mingw-w64-headers-bootstrap
yaourt --needed --noconfirm -S mkinitcpio-numlock
yaourt --needed --noconfirm -S muffin-git
yaourt --needed --noconfirm -S nemo-fm
yaourt --needed --noconfirm -S nvidia-source-beta
yaourt --needed --noconfirm -S nvidia-utils-beta
yaourt --needed --noconfirm -S oneko
yaourt --needed --noconfirm -S openssl098
yaourt --needed --noconfirm -S package-query
yaourt --needed --noconfirm -S pacman-color
yaourt --needed --noconfirm -S pasteall
yaourt --needed --noconfirm -S perl-weather-underground
yaourt --needed --noconfirm -S profile-cleaner
yaourt --needed --noconfirm -S python-pyalsaaudio
yaourt --needed --noconfirm -S python-pygame
yaourt --needed --noconfirm -S qjoypad
yaourt --needed --noconfirm -S r8168-dkms
yaourt --needed --noconfirm -S rakarrack
yaourt --needed --noconfirm -S read-edid
yaourt --needed --noconfirm -S repo-git
yaourt --needed --noconfirm -S retext
yaourt --needed --noconfirm -S screengrab
yaourt --needed --noconfirm -S sfxr
yaourt --needed --noconfirm -S tleds
yaourt --needed --noconfirm -S ttf-ms-fonts
yaourt --needed --noconfirm -S ubuntu-sounds
yaourt --needed --noconfirm -S usbmon
yaourt --needed --noconfirm -S weatherspect
yaourt --needed --noconfirm -S wine-mono-bin
yaourt --needed --noconfirm -S winetricks-svn
yaourt --needed --noconfirm -S xarchiver-xz
yaourt --needed --noconfirm -S xrdp
yaourt --needed --noconfirm -S xvidcap
yaourt --needed --noconfirm -S xxd
yaourt --needed --noconfirm -S yad
yaourt --needed --noconfirm -S yaourt
