#!/bin/bash

yaourt --needed --noconfirm -S aewan
yaourt --needed --noconfirm -S alacarte-xfce
yaourt --needed --noconfirm -S alsaequal
yaourt --needed --noconfirm -S alsaequal-mgr
yaourt --needed --noconfirm -S alsamixergui
yaourt --needed --noconfirm -S android-apktool
yaourt --needed --noconfirm -S android-ndk
yaourt --needed --noconfirm -S android-sdk
yaourt --needed --noconfirm -S android-sdk-platform-tools
yaourt --needed --noconfirm -S ascii-invaders
yaourt --needed --noconfirm -S asciiquarium
yaourt --needed --noconfirm -S bacon
yaourt --needed --noconfirm -S bash-game-manager
yaourt --needed --noconfirm -S boxfs
yaourt --needed --noconfirm -S caps
yaourt --needed --noconfirm -S cdspeed
yaourt --needed --noconfirm -S cpuled
yaourt --needed --noconfirm -S detourious-svn
yaourt --needed --noconfirm -S dex2jar
yaourt --needed --noconfirm -S downgrade
yaourt --needed --noconfirm -S ext4_utils
yaourt --needed --noconfirm -S flrec
yaourt --needed --noconfirm -S fltk11
yaourt --needed --noconfirm -S fortune-mod-br
yaourt --needed --noconfirm -S freerapid
yaourt --needed --noconfirm -S freetype2-lcd
yaourt --needed --noconfirm -S geany-git
yaourt --needed --noconfirm -S geany-plugins-git
yaourt --needed --noconfirm -S geany-themes-git
yaourt --needed --noconfirm -S gedit-pkgbuild-highlight
yaourt --needed --noconfirm -S gedit-solarized-git
yaourt --needed --noconfirm -S glew1.5
yaourt --needed --noconfirm -S gmtp
yaourt --needed --noconfirm -S gnome-colors-icon-theme
yaourt --needed --noconfirm -S gnome-colors-icon-theme-extras
yaourt --needed --noconfirm -S gtk-engine-equinox
yaourt --needed --noconfirm -S gtk-rezlooks-engine
yaourt --needed --noconfirm -S gtkglarea
yaourt --needed --noconfirm -S gvolwheel
yaourt --needed --noconfirm -S iocane
yaourt --needed --noconfirm -S irpf
yaourt --needed --noconfirm -S jre6
yaourt --needed --noconfirm -S key-mon
yaourt --needed --noconfirm -S ksh
yaourt --needed --noconfirm -S lib32-alsaequal
yaourt --needed --noconfirm -S lib32-caps
yaourt --needed --noconfirm -S lib32-fuse
yaourt --needed --noconfirm -S lib32-glew1.5
yaourt --needed --noconfirm -S lib32-ladspa
yaourt --needed --noconfirm -S lib32-libjpeg6
yaourt --needed --noconfirm -S lib32-libxxf86dga
yaourt --needed --noconfirm -S libapp-git
yaourt --needed --noconfirm -S libgksu-no-remember-pass
yaourt --needed --noconfirm -S libjpeg6
yaourt --needed --noconfirm -S libtiff3
yaourt --needed --noconfirm -S libvorbis-aotuv
yaourt --needed --noconfirm -S libxnvctrl
yaourt --needed --noconfirm -S mingw32-zlib
yaourt --needed --noconfirm -S mkinitcpio-numlock
yaourt --needed --noconfirm -S oneko
yaourt --needed --noconfirm -S openssl098
yaourt --needed --noconfirm -S package-query
yaourt --needed --noconfirm -S pasteall
yaourt --needed --noconfirm -S perl-weather-underground
yaourt --needed --noconfirm -S phatch
yaourt --needed --noconfirm -S profile-cleaner
yaourt --needed --noconfirm -S python-markups
yaourt --needed --noconfirm -S python-pyalsaaudio
yaourt --needed --noconfirm -S python-pygame
yaourt --needed --noconfirm -S r8168-ck
yaourt --needed --noconfirm -S rakarrack
yaourt --needed --noconfirm -S rar
yaourt --needed --noconfirm -S read-edid
yaourt --needed --noconfirm -S receitanet
yaourt --needed --noconfirm -S repo
yaourt --needed --noconfirm -S retext
yaourt --needed --noconfirm -S sfxr
yaourt --needed --noconfirm -S tleds
yaourt --needed --noconfirm -S ttf-ms-fonts
yaourt --needed --noconfirm -S ubuntu-sounds
yaourt --needed --noconfirm -S usbmon
yaourt --needed --noconfirm -S vice-gtkglext
yaourt --needed --noconfirm -S vlmc-git
yaourt --needed --noconfirm -S watermelons
yaourt --needed --noconfirm -S weatherspect
yaourt --needed --noconfirm -S wine-mono-bin
yaourt --needed --noconfirm -S winetricks-svn
yaourt --needed --noconfirm -S xarchiver-xz
yaourt --needed --noconfirm -S xfce4-netspeed-plugin-svn
yaourt --needed --noconfirm -S xfwm4-tiling
yaourt --needed --noconfirm -S xrdp
yaourt --needed --noconfirm -S xvidcap
yaourt --needed --noconfirm -S xxd
yaourt --needed --noconfirm -S yad
yaourt --needed --noconfirm -S yaourt
