#!/bin/bash

pacman --needed --noconfirm -S abs
pacman --needed --noconfirm -S alsa-firmware
pacman --needed --noconfirm -S alsa-lib
pacman --needed --noconfirm -S alsa-oss
pacman --needed --noconfirm -S alsa-plugins
pacman --needed --noconfirm -S alsa-utils
pacman --needed --noconfirm -S amd-ucode
pacman --needed --noconfirm -S arch-install-scripts
pacman --needed --noconfirm -S armagetronad
pacman --needed --noconfirm -S audit
pacman --needed --noconfirm -S autoconf
pacman --needed --noconfirm -S automake
pacman --needed --noconfirm -S axel
pacman --needed --noconfirm -S bash
pacman --needed --noconfirm -S bash-completion
pacman --needed --noconfirm -S bc
pacman --needed --noconfirm -S bftpd
pacman --needed --noconfirm -S binutils-multilib
pacman --needed --noconfirm -S bison
pacman --needed --noconfirm -S blender
pacman --needed --noconfirm -S boost
pacman --needed --noconfirm -S boost-libs
pacman --needed --noconfirm -S bsdiff
pacman --needed --noconfirm -S bzip2
pacman --needed --noconfirm -S bzr
pacman --needed --noconfirm -S ccache
pacman --needed --noconfirm -S celt
pacman --needed --noconfirm -S cmake
pacman --needed --noconfirm -S colorgcc
pacman --needed --noconfirm -S coreutils
pacman --needed --noconfirm -S cpio
pacman --needed --noconfirm -S cpupower
pacman --needed --noconfirm -S cryptsetup
pacman --needed --noconfirm -S curl
pacman --needed --noconfirm -S curlftpfs
pacman --needed --noconfirm -S davfs2
pacman --needed --noconfirm -S dbus
pacman --needed --noconfirm -S deadbeef
pacman --needed --noconfirm -S device-mapper
pacman --needed --noconfirm -S devil
pacman --needed --noconfirm -S dhcpcd
pacman --needed --noconfirm -S diffutils
pacman --needed --noconfirm -S dillo
pacman --needed --noconfirm -S dkms
pacman --needed --noconfirm -S dmidecode
pacman --needed --noconfirm -S dnsutils
pacman --needed --noconfirm -S dosbox
pacman --needed --noconfirm -S dosfstools
pacman --needed --noconfirm -S dvdrtools
pacman --needed --noconfirm -S dzen2
pacman --needed --noconfirm -S e2fsprogs
pacman --needed --noconfirm -S easytag
pacman --needed --noconfirm -S epdfview
pacman --needed --noconfirm -S ethtool
pacman --needed --noconfirm -S exo
pacman --needed --noconfirm -S expect
pacman --needed --noconfirm -S fakeroot
pacman --needed --noconfirm -S fbpanel
pacman --needed --noconfirm -S ffmpeg
pacman --needed --noconfirm -S file
pacman --needed --noconfirm -S filesystem
pacman --needed --noconfirm -S findutils
pacman --needed --noconfirm -S firefox
pacman --needed --noconfirm -S firefox-i18n-pt-br
pacman --needed --noconfirm -S flashplugin
pacman --needed --noconfirm -S flex
pacman --needed --noconfirm -S fortune-mod
pacman --needed --noconfirm -S fping
pacman --needed --noconfirm -S freealut
pacman --needed --noconfirm -S fuseiso
pacman --needed --noconfirm -S garcon
pacman --needed --noconfirm -S gawk
pacman --needed --noconfirm -S gcc-multilib
pacman --needed --noconfirm -S gconf-editor
pacman --needed --noconfirm -S gdb
pacman --needed --noconfirm -S gedit
pacman --needed --noconfirm -S gedit-plugins
pacman --needed --noconfirm -S geoip
pacman --needed --noconfirm -S gettext
pacman --needed --noconfirm -S gftp
pacman --needed --noconfirm -S ghostscript
pacman --needed --noconfirm -S gimp
pacman --needed --noconfirm -S gimp-dbp
pacman --needed --noconfirm -S git
pacman --needed --noconfirm -S gjs
pacman --needed --noconfirm -S glade
pacman --needed --noconfirm -S glib
pacman --needed --noconfirm -S glib2
pacman --needed --noconfirm -S glibc
pacman --needed --noconfirm -S gnome-keyring
pacman --needed --noconfirm -S gnu-netcat
pacman --needed --noconfirm -S gparted
pacman --needed --noconfirm -S gperf
pacman --needed --noconfirm -S gpicview
pacman --needed --noconfirm -S grep
pacman --needed --noconfirm -S gstreamer0.10
pacman --needed --noconfirm -S gstreamer0.10-bad
pacman --needed --noconfirm -S gstreamer0.10-bad-plugins
pacman --needed --noconfirm -S gstreamer0.10-base
pacman --needed --noconfirm -S gstreamer0.10-base-plugins
pacman --needed --noconfirm -S gstreamer0.10-ffmpeg
pacman --needed --noconfirm -S gstreamer0.10-good
pacman --needed --noconfirm -S gstreamer0.10-python
pacman --needed --noconfirm -S gstreamer0.10-ugly
pacman --needed --noconfirm -S gstreamer0.10-ugly-plugins
pacman --needed --noconfirm -S gtk
pacman --needed --noconfirm -S gtk-engine-murrine
pacman --needed --noconfirm -S gtk-engine-unico
pacman --needed --noconfirm -S gtk-engines
pacman --needed --noconfirm -S gtk2
pacman --needed --noconfirm -S gtk2-xfce-engine
pacman --needed --noconfirm -S gtk3-xfce-engine
pacman --needed --noconfirm -S guake
pacman --needed --noconfirm -S gucharmap
pacman --needed --noconfirm -S gvfs
pacman --needed --noconfirm -S gvfs-afc
pacman --needed --noconfirm -S gvfs-mtp
pacman --needed --noconfirm -S gzip
pacman --needed --noconfirm -S hdparm
pacman --needed --noconfirm -S hexedit
pacman --needed --noconfirm -S htop
pacman --needed --noconfirm -S inetutils
pacman --needed --noconfirm -S iproute2
pacman --needed --noconfirm -S iptables
pacman --needed --noconfirm -S iptraf-ng
pacman --needed --noconfirm -S iputils
pacman --needed --noconfirm -S jack
pacman --needed --noconfirm -S jad
pacman --needed --noconfirm -S jfsutils
pacman --needed --noconfirm -S keychain
pacman --needed --noconfirm -S less
pacman --needed --noconfirm -S lib32-alsa-lib
pacman --needed --noconfirm -S lib32-alsa-plugins
pacman --needed --noconfirm -S lib32-cairo
pacman --needed --noconfirm -S lib32-curl
pacman --needed --noconfirm -S lib32-freetype2
pacman --needed --noconfirm -S lib32-glew
pacman --needed --noconfirm -S lib32-glu
pacman --needed --noconfirm -S lib32-gtk
pacman --needed --noconfirm -S lib32-lcms
pacman --needed --noconfirm -S lib32-libcanberra
pacman --needed --noconfirm -S lib32-libmikmod
pacman --needed --noconfirm -S lib32-libpng
pacman --needed --noconfirm -S lib32-libstdc++5
pacman --needed --noconfirm -S lib32-libxml2
pacman --needed --noconfirm -S lib32-mpg123
pacman --needed --noconfirm -S lib32-nss
pacman --needed --noconfirm -S lib32-nvidia-libgl
pacman --needed --noconfirm -S lib32-openal
pacman --needed --noconfirm -S lib32-qt4
pacman --needed --noconfirm -S lib32-sdl
pacman --needed --noconfirm -S lib32-sdl_image
pacman --needed --noconfirm -S lib32-sdl_ttf
pacman --needed --noconfirm -S libcanberra
pacman --needed --noconfirm -S libcanberra-gstreamer
pacman --needed --noconfirm -S libffado
pacman --needed --noconfirm -S libfm
pacman --needed --noconfirm -S libgnome-keyring
pacman --needed --noconfirm -S libnet
pacman --needed --noconfirm -S libopenraw
pacman --needed --noconfirm -S libtool-multilib
pacman --needed --noconfirm -S libvdpau
pacman --needed --noconfirm -S libvncserver
pacman --needed --noconfirm -S libwacom
pacman --needed --noconfirm -S libx11
pacman --needed --noconfirm -S libxfce4ui
pacman --needed --noconfirm -S libxfce4util
pacman --needed --noconfirm -S licenses
pacman --needed --noconfirm -S links
pacman --needed --noconfirm -S linux-ck-k10
pacman --needed --noconfirm -S linux-ck-k10-headers
pacman --needed --noconfirm -S lrzip
pacman --needed --noconfirm -S lsof
pacman --needed --noconfirm -S lxappearance
pacman --needed --noconfirm -S make
pacman --needed --noconfirm -S man-db
pacman --needed --noconfirm -S man-pages
pacman --needed --noconfirm -S mdadm
pacman --needed --noconfirm -S meld
pacman --needed --noconfirm -S mencoder
pacman --needed --noconfirm -S mesa-demos
pacman --needed --noconfirm -S mingw32-gcc
pacman --needed --noconfirm -S mixxx
pacman --needed --noconfirm -S mkinitcpio
pacman --needed --noconfirm -S mlocate
pacman --needed --noconfirm -S motion
pacman --needed --noconfirm -S mpg123
pacman --needed --noconfirm -S mplayer
pacman --needed --noconfirm -S mtools
pacman --needed --noconfirm -S namcap
pacman --needed --noconfirm -S nano
pacman --needed --noconfirm -S nmap
pacman --needed --noconfirm -S noip
pacman --needed --noconfirm -S ntfs-3g
pacman --needed --noconfirm -S ntp
pacman --needed --noconfirm -S numlockx
pacman --needed --noconfirm -S nvidia-ck-k10
pacman --needed --noconfirm -S openal
pacman --needed --noconfirm -S opencl-nvidia
pacman --needed --noconfirm -S openshot
pacman --needed --noconfirm -S openssh
pacman --needed --noconfirm -S optipng
pacman --needed --noconfirm -S p7zip
pacman --needed --noconfirm -S pacman
pacman --needed --noconfirm -S pangox-compat
pacman --needed --noconfirm -S patch
pacman --needed --noconfirm -S pciutils
pacman --needed --noconfirm -S pcmciautils
pacman --needed --noconfirm -S perl
pacman --needed --noconfirm -S perl-json
pacman --needed --noconfirm -S pkg-config
pacman --needed --noconfirm -S pkgfile
pacman --needed --noconfirm -S polkit-gnome
pacman --needed --noconfirm -S prelink
pacman --needed --noconfirm -S procps-ng
pacman --needed --noconfirm -S psmisc
pacman --needed --noconfirm -S pygtksourceview2
pacman --needed --noconfirm -S python
pacman --needed --noconfirm -S python-beautifulsoup4
pacman --needed --noconfirm -S python-dbus
pacman --needed --noconfirm -S python-distribute
pacman --needed --noconfirm -S python-distutils-extra
pacman --needed --noconfirm -S python-gobject
pacman --needed --noconfirm -S python-gobject2
pacman --needed --noconfirm -S python-httplib2
pacman --needed --noconfirm -S python-psutil
pacman --needed --noconfirm -S python2
pacman --needed --noconfirm -S python2-gconf
pacman --needed --noconfirm -S python2-gobject
pacman --needed --noconfirm -S python2-imaging
pacman --needed --noconfirm -S python2-lxml
pacman --needed --noconfirm -S python2-notify
pacman --needed --noconfirm -S python2-numpy
pacman --needed --noconfirm -S python2-pyinotify
pacman --needed --noconfirm -S python2-pyqt4
pacman --needed --noconfirm -S python2-xdg
pacman --needed --noconfirm -S pywebkitgtk
pacman --needed --noconfirm -S qjackctl
pacman --needed --noconfirm -S rdesktop
pacman --needed --noconfirm -S reiserfsprogs
pacman --needed --noconfirm -S rpmextract
pacman --needed --noconfirm -S samba
pacman --needed --noconfirm -S schedtool
pacman --needed --noconfirm -S scons
pacman --needed --noconfirm -S sdl_mixer
pacman --needed --noconfirm -S sed
pacman --needed --noconfirm -S shadow
pacman --needed --noconfirm -S skype
pacman --needed --noconfirm -S sniffit
pacman --needed --noconfirm -S sound-theme-freedesktop
pacman --needed --noconfirm -S steam
pacman --needed --noconfirm -S steghide
pacman --needed --noconfirm -S strace
pacman --needed --noconfirm -S subversion
pacman --needed --noconfirm -S sudo
pacman --needed --noconfirm -S swh-plugins
pacman --needed --noconfirm -S swig
pacman --needed --noconfirm -S swt
pacman --needed --noconfirm -S sysfsutils
pacman --needed --noconfirm -S syslinux
pacman --needed --noconfirm -S systemd
pacman --needed --noconfirm -S tar
pacman --needed --noconfirm -S tcpdump
pacman --needed --noconfirm -S terminus-font
pacman --needed --noconfirm -S texinfo
pacman --needed --noconfirm -S thunar
pacman --needed --noconfirm -S thunar-archive-plugin
pacman --needed --noconfirm -S thunar-media-tags-plugin
pacman --needed --noconfirm -S thunar-volman
pacman --needed --noconfirm -S traceroute
pacman --needed --noconfirm -S transcode
pacman --needed --noconfirm -S tree
pacman --needed --noconfirm -S tumbler
pacman --needed --noconfirm -S tzdata
pacman --needed --noconfirm -S unetbootin
pacman --needed --noconfirm -S unrar
pacman --needed --noconfirm -S upower
pacman --needed --noconfirm -S upx
pacman --needed --noconfirm -S usbutils
pacman --needed --noconfirm -S util-linux
pacman --needed --noconfirm -S vi
pacman --needed --noconfirm -S vorbis-tools
pacman --needed --noconfirm -S webkitgtk
pacman --needed --noconfirm -S webkitgtk2
pacman --needed --noconfirm -S wget
pacman --needed --noconfirm -S which
pacman --needed --noconfirm -S whois
pacman --needed --noconfirm -S wine
pacman --needed --noconfirm -S wine_gecko
pacman --needed --noconfirm -S wmctrl
pacman --needed --noconfirm -S wpa_supplicant
pacman --needed --noconfirm -S wxcam
pacman --needed --noconfirm -S x11vnc
pacman --needed --noconfirm -S xcursor-bluecurve
pacman --needed --noconfirm -S xfce4-appfinder
pacman --needed --noconfirm -S xfce4-mixer
pacman --needed --noconfirm -S xfce4-panel
pacman --needed --noconfirm -S xfce4-power-manager
pacman --needed --noconfirm -S xfce4-screenshooter
pacman --needed --noconfirm -S xfce4-session
pacman --needed --noconfirm -S xfce4-settings
pacman --needed --noconfirm -S xfdesktop
pacman --needed --noconfirm -S xfsprogs
pacman --needed --noconfirm -S xfwm4-themes
pacman --needed --noconfirm -S xorg-bdftopcf
pacman --needed --noconfirm -S xorg-docs
pacman --needed --noconfirm -S xorg-font-util
pacman --needed --noconfirm -S xorg-fonts-100dpi
pacman --needed --noconfirm -S xorg-fonts-75dpi
pacman --needed --noconfirm -S xorg-fonts-cyrillic
pacman --needed --noconfirm -S xorg-fonts-encodings
pacman --needed --noconfirm -S xorg-iceauth
pacman --needed --noconfirm -S xorg-luit
pacman --needed --noconfirm -S xorg-mkfontdir
pacman --needed --noconfirm -S xorg-mkfontscale
pacman --needed --noconfirm -S xorg-server
pacman --needed --noconfirm -S xorg-server-common
pacman --needed --noconfirm -S xorg-server-utils
pacman --needed --noconfirm -S xorg-sessreg
pacman --needed --noconfirm -S xorg-setxkbmap
pacman --needed --noconfirm -S xorg-smproxy
pacman --needed --noconfirm -S xorg-utils
pacman --needed --noconfirm -S xorg-x11perf
pacman --needed --noconfirm -S xorg-xauth
pacman --needed --noconfirm -S xorg-xbacklight
pacman --needed --noconfirm -S xorg-xclock
pacman --needed --noconfirm -S xorg-xcmsdb
pacman --needed --noconfirm -S xorg-xcursorgen
pacman --needed --noconfirm -S xorg-xdpyinfo
pacman --needed --noconfirm -S xorg-xdriinfo
pacman --needed --noconfirm -S xorg-xev
pacman --needed --noconfirm -S xorg-xfontsel
pacman --needed --noconfirm -S xorg-xgamma
pacman --needed --noconfirm -S xorg-xhost
pacman --needed --noconfirm -S xorg-xinit
pacman --needed --noconfirm -S xorg-xinput
pacman --needed --noconfirm -S xorg-xkbcomp
pacman --needed --noconfirm -S xorg-xkbevd
pacman --needed --noconfirm -S xorg-xkbutils
pacman --needed --noconfirm -S xorg-xkill
pacman --needed --noconfirm -S xorg-xlsatoms
pacman --needed --noconfirm -S xorg-xlsclients
pacman --needed --noconfirm -S xorg-xmessage
pacman --needed --noconfirm -S xorg-xmodmap
pacman --needed --noconfirm -S xorg-xpr
pacman --needed --noconfirm -S xorg-xprop
pacman --needed --noconfirm -S xorg-xrandr
pacman --needed --noconfirm -S xorg-xrdb
pacman --needed --noconfirm -S xorg-xrefresh
pacman --needed --noconfirm -S xorg-xset
pacman --needed --noconfirm -S xorg-xsetroot
pacman --needed --noconfirm -S xorg-xvinfo
pacman --needed --noconfirm -S xorg-xwd
pacman --needed --noconfirm -S xorg-xwininfo
pacman --needed --noconfirm -S xorg-xwud
pacman --needed --noconfirm -S zip
