#!/bin/bash

pacman --needed --noconfirm abs alsa-firmware alsa-lib
pacman --needed --noconfirm alsa-oss alsa-plugins alsa-utils
pacman --needed --noconfirm amd-ucode archlinux-themes-kdm armagetronad
pacman --needed --noconfirm audit autoconf automake
pacman --needed --noconfirm axel bash bash-completion
pacman --needed --noconfirm bc binutils-multilib blender
pacman --needed --noconfirm boost boost-libs bsdiff
pacman --needed --noconfirm bzip2 bzr calligra-l10n-pt_br
pacman --needed --noconfirm calligra-sheets cmake coreutils
pacman --needed --noconfirm cpupower cryptsetup cuda-toolkit
pacman --needed --noconfirm curl dbus dbus-core
pacman --needed --noconfirm deadbeef device-mapper devil
pacman --needed --noconfirm dhcpcd diffutils dmidecode
pacman --needed --noconfirm dnsutils dosfstools dzen2
pacman --needed --noconfirm e2fsprogs emesene epdfview
pacman --needed --noconfirm expect fakeroot fbpanel
pacman --needed --noconfirm ffmpeg file filesystem
pacman --needed --noconfirm findutils firefox firefox-i18n-pt-br
pacman --needed --noconfirm flashplugin fping freealut
pacman --needed --noconfirm gawk gcc-multilib gconf-editor
pacman --needed --noconfirm gdb geoip gettext
pacman --needed --noconfirm gimp git gksu
pacman --needed --noconfirm glade glib glib2
pacman --needed --noconfirm glibc gmrun gnome-packagekit
pacman --needed --noconfirm gnu-netcat gparted grep
pacman --needed --noconfirm gstreamer0.10 gstreamer0.10-bad gstreamer0.10-bad-plugins
pacman --needed --noconfirm gstreamer0.10-base gstreamer0.10-base-plugins gstreamer0.10-ffmpeg
pacman --needed --noconfirm gstreamer0.10-good gstreamer0.10-good-plugins gstreamer0.10-ugly
pacman --needed --noconfirm gstreamer0.10-ugly-plugins gthumb gtk
pacman --needed --noconfirm gtk-engine-murrine gtk-engine-unico gtk-engines
pacman --needed --noconfirm gtk2 gzip hardinfo
pacman --needed --noconfirm hdparm heirloom-mailx hping
pacman --needed --noconfirm htop hydrogen icedtea-web-java7
pacman --needed --noconfirm inetutils iproute2 iptables
pacman --needed --noconfirm iptraf-ng iputils jack
pacman --needed --noconfirm jdk7-openjdk jfsutils jre7-openjdk
pacman --needed --noconfirm kde-l10n-pt_br kde-wallpapers kdebase-dolphin
pacman --needed --noconfirm kdebase-kdepasswd kdebase-kdialog kdebase-konsole
pacman --needed --noconfirm kdebase-plasma kdegraphics-kgamma kdegraphics-ksnapshot
pacman --needed --noconfirm kdenlive kdeplasma-addons-applets-eyes kdeplasma-addons-applets-notes
pacman --needed --noconfirm kmess ktorrent less
pacman --needed --noconfirm lib32-alsa-lib lib32-alsa-plugins lib32-freetype2
pacman --needed --noconfirm lib32-glew lib32-libcanberra-pulse lib32-libpng
pacman --needed --noconfirm lib32-libpulse lib32-libxml2 lib32-mpg123
pacman --needed --noconfirm lib32-openal lib32-sdl lib32-sdl_image
pacman --needed --noconfirm lib32-sdl_ttf libcanberra libgdata
pacman --needed --noconfirm libgnome-keyring libmate libmatecanvas
pacman --needed --noconfirm libmatecomponent libmatecomponentui libmatekbd
pacman --needed --noconfirm libmatekeyring libmatenotify libmateui
pacman --needed --noconfirm libmateweather libmatewnck libnet
pacman --needed --noconfirm libtool-multilib libvdpau libwebkit
pacman --needed --noconfirm libwebkit3 libx11 licenses
pacman --needed --noconfirm links linux-ck-kx linux-ck-kx-headers
pacman --needed --noconfirm lm_sensors luxblend25 lvm2
pacman --needed --noconfirm lxappearance make man-db
pacman --needed --noconfirm man-pages mari0 mate-applets
pacman --needed --noconfirm mate-backgrounds mate-common mate-conf
pacman --needed --noconfirm mate-control-center mate-corba mate-desktop
pacman --needed --noconfirm mate-dialogs mate-doc-utils mate-file-manager
pacman --needed --noconfirm mate-icon-theme mate-keyring mate-media
pacman --needed --noconfirm mate-menu-editor mate-menus mate-mime-data
pacman --needed --noconfirm mate-notification-daemon mate-panel mate-polkit
pacman --needed --noconfirm mate-session-manager mate-settings-daemon mate-themes
pacman --needed --noconfirm mate-vfs mate-window-manager mdadm
pacman --needed --noconfirm meld mencoder mesa-demos
pacman --needed --noconfirm mingetty mixxx mkinitcpio
pacman --needed --noconfirm mlocate mpg123 mplayer
pacman --needed --noconfirm namcap nano nawk
pacman --needed --noconfirm nmap ntfsprogs numlockx
pacman --needed --noconfirm openal openssh p7zip
pacman --needed --noconfirm pacman paprefs patch
pacman --needed --noconfirm pavucontrol pciutils pcmanfm
pacman --needed --noconfirm pcmciautils perl phonon-vlc
pacman --needed --noconfirm pkg-config pkgfile pkgstats
pacman --needed --noconfirm ppp prelink preload
pacman --needed --noconfirm procps-ng psmisc pulseaudio-alsa
pacman --needed --noconfirm pygtksourceview2 pypanel python
pacman --needed --noconfirm python-dbus python-distribute python-distutils-extra
pacman --needed --noconfirm python-gobject python-gobject2 python-mate
pacman --needed --noconfirm python-mate-desktop python2 python2-gconf
pacman --needed --noconfirm python2-numpy python2-pyinotify python2-pyqt
pacman --needed --noconfirm python2-xdg qjackctl reiserfsprogs
pacman --needed --noconfirm ristretto samba schedtool
pacman --needed --noconfirm scons sdl_mixer sed
pacman --needed --noconfirm shadow skype sniffit
pacman --needed --noconfirm sound-theme-freedesktop spacefm steghide
pacman --needed --noconfirm strace sudo swftools
pacman --needed --noconfirm swh-plugins swig sysfsutils
pacman --needed --noconfirm syslinux syslog-ng systemd
pacman --needed --noconfirm tar tcpdump terminal
pacman --needed --noconfirm terminus-font texinfo traceroute
pacman --needed --noconfirm transcode tumbler tzdata
pacman --needed --noconfirm udisks unrar upower
pacman --needed --noconfirm upx usbutils util-linux
pacman --needed --noconfirm vi vidalia vlc
pacman --needed --noconfirm vorbis-tools wget which
pacman --needed --noconfirm whois wine wine_gecko
pacman --needed --noconfirm wmctrl wpa_supplicant xfburn
pacman --needed --noconfirm xfsprogs xnee xorg-bdftopcf
pacman --needed --noconfirm xorg-docs xorg-font-util xorg-fonts-100dpi
pacman --needed --noconfirm xorg-fonts-75dpi xorg-fonts-cyrillic xorg-fonts-encodings
pacman --needed --noconfirm xorg-iceauth xorg-luit xorg-mkfontdir
pacman --needed --noconfirm xorg-mkfontscale xorg-server xorg-server-common
pacman --needed --noconfirm xorg-server-utils xorg-sessreg xorg-setxkbmap
pacman --needed --noconfirm xorg-smproxy xorg-utils xorg-x11perf
pacman --needed --noconfirm xorg-xauth xorg-xbacklight xorg-xclock
pacman --needed --noconfirm xorg-xcmsdb xorg-xcursorgen xorg-xdpyinfo
pacman --needed --noconfirm xorg-xdriinfo xorg-xev xorg-xgamma
pacman --needed --noconfirm xorg-xhost xorg-xinit xorg-xinput
pacman --needed --noconfirm xorg-xkbcomp xorg-xkbevd xorg-xkbutils
pacman --needed --noconfirm xorg-xkill xorg-xlsatoms xorg-xlsclients
pacman --needed --noconfirm xorg-xmessage xorg-xmodmap xorg-xpr
pacman --needed --noconfirm xorg-xprop xorg-xrandr xorg-xrdb
pacman --needed --noconfirm xorg-xrefresh xorg-xset xorg-xsetroot
pacman --needed --noconfirm xorg-xvinfo xorg-xwd xorg-xwininfo
pacman --needed --noconfirm xorg-xwud xulrunner zip