#!/bin/bash

pacman --needed --noconfirm abs alsa-firmware alsa-lib
pacman --needed --noconfirm alsa-oss alsa-plugins alsa-utils
pacman --needed --noconfirm amd-ucode archlinux-themes-kdm armagetronad
pacman --needed --noconfirm audit autoconf automake
pacman --needed --noconfirm axel bash bash-completion
pacman --needed --noconfirm bc binutils-multilib blender
pacman --needed --noconfirm boinc boost boost-libs
pacman --needed --noconfirm bsdiff bzip2 bzr
pacman --needed --noconfirm calligra-l10n-pt_br calligra-sheets cmake
pacman --needed --noconfirm consolekit coreutils cryptsetup
pacman --needed --noconfirm cuda-toolkit curl dbus
pacman --needed --noconfirm dbus-core deadbeef device-mapper
pacman --needed --noconfirm devil dhcpcd diffutils
pacman --needed --noconfirm dmidecode dnsutils dosfstools
pacman --needed --noconfirm dzen2 e2fsprogs emesene
pacman --needed --noconfirm epdfview expect fakeroot
pacman --needed --noconfirm fbpanel ffmpeg file
pacman --needed --noconfirm filesystem findutils firefox
pacman --needed --noconfirm firefox-i18n-pt-br flashplugin fping
pacman --needed --noconfirm freealut gawk gcc-multilib
pacman --needed --noconfirm gconf-editor gdb geoip
pacman --needed --noconfirm gettext gimp git
pacman --needed --noconfirm glade glib glib2
pacman --needed --noconfirm glibc gmrun gnu-netcat
pacman --needed --noconfirm gparted grep gstreamer0.10
pacman --needed --noconfirm gstreamer0.10-bad gstreamer0.10-bad-plugins gstreamer0.10-base
pacman --needed --noconfirm gstreamer0.10-base-plugins gstreamer0.10-ffmpeg gstreamer0.10-good
pacman --needed --noconfirm gstreamer0.10-good-plugins gstreamer0.10-ugly gstreamer0.10-ugly-plugins
pacman --needed --noconfirm gthumb gtk gtk-engine-murrine
pacman --needed --noconfirm gtk-engine-unico gtk-engines gtk2
pacman --needed --noconfirm gzip hardinfo hdparm
pacman --needed --noconfirm heirloom-mailx hping htop
pacman --needed --noconfirm hydrogen icedtea-web-java7 inetutils
pacman --needed --noconfirm iproute2 iptables iptraf-ng
pacman --needed --noconfirm iputils jack jfsutils
pacman --needed --noconfirm jre7-openjdk kde-l10n-pt_br kde-wallpapers
pacman --needed --noconfirm kdebase-dolphin kdebase-kdepasswd kdebase-kdialog
pacman --needed --noconfirm kdebase-konsole kdebase-plasma kdegraphics-kgamma
pacman --needed --noconfirm kdegraphics-ksnapshot kdemultimedia-kmix kdenlive
pacman --needed --noconfirm kdeplasma-addons-applets-eyes kdeplasma-addons-applets-notes kmess
pacman --needed --noconfirm less lib32-alsa-lib lib32-alsa-plugins
pacman --needed --noconfirm lib32-libcanberra-pulse lib32-libpng lib32-libpulse
pacman --needed --noconfirm lib32-libxml2 lib32-mpg123 lib32-openal
pacman --needed --noconfirm lib32-sdl libcanberra libgdata
pacman --needed --noconfirm libgnome-keyring libnet libtool-multilib
pacman --needed --noconfirm libvdpau libwebkit libwebkit3
pacman --needed --noconfirm libx11 licenses links
pacman --needed --noconfirm linux linux-headers linux-zen
pacman --needed --noconfirm linux-zen-headers lm_sensors luxblend25
pacman --needed --noconfirm lvm2 lxappearance lxappearance-obconf
pacman --needed --noconfirm make man-db man-pages
pacman --needed --noconfirm mdadm meld mencoder
pacman --needed --noconfirm mesa-demos mingetty mkinitcpio
pacman --needed --noconfirm mlocate mpg123 mplayer
pacman --needed --noconfirm namcap nano nawk
pacman --needed --noconfirm nmap ntfsprogs numlockx
pacman --needed --noconfirm obconf obmenu openal
pacman --needed --noconfirm openbox openssh p7zip
pacman --needed --noconfirm pacman paprefs patch
pacman --needed --noconfirm pavucontrol pciutils pcmanfm
pacman --needed --noconfirm pcmciautils perl phonon-vlc
pacman --needed --noconfirm pkg-config pkgfile pkgstats
pacman --needed --noconfirm ppp prelink preload
pacman --needed --noconfirm procps-ng psmisc pulseaudio-alsa
pacman --needed --noconfirm pygtksourceview2 pypanel python
pacman --needed --noconfirm python-dbus python-distribute python-distutils-extra
pacman --needed --noconfirm python-gobject python-gobject2 python-pygame
pacman --needed --noconfirm python-wnck python2 python2-gconf
pacman --needed --noconfirm python2-numpy python2-pyinotify python2-pyqt
pacman --needed --noconfirm python2-xdg qjackctl reiserfsprogs
pacman --needed --noconfirm ristretto samba schedtool
pacman --needed --noconfirm scons sdl_mixer sed
pacman --needed --noconfirm shadow skype sniffit
pacman --needed --noconfirm sound-theme-freedesktop spacefm steghide
pacman --needed --noconfirm strace sudo swftools
pacman --needed --noconfirm swh-plugins swig sysfsutils
pacman --needed --noconfirm syslinux syslog-ng systemd
pacman --needed --noconfirm tar tcpdump terminus-font
pacman --needed --noconfirm texinfo tilda traceroute
pacman --needed --noconfirm transcode tumbler tzdata
pacman --needed --noconfirm udisks unrar upower
pacman --needed --noconfirm upx usbutils util-linux
pacman --needed --noconfirm vi vidalia vlc
pacman --needed --noconfirm vorbis-tools wget which
pacman --needed --noconfirm whois wine wine_gecko
pacman --needed --noconfirm wmctrl wpa_supplicant xfburn
pacman --needed --noconfirm xfsprogs xnee xorg-bdftopcf
pacman --needed --noconfirm xorg-docs xorg-font-util xorg-fonts-100dpi
pacman --needed --noconfirm xorg-fonts-75dpi xorg-fonts-cyrillic xorg-fonts-encodings
pacman --needed --noconfirm xorg-iceauth xorg-luit xorg-mkfontdir
pacman --needed --noconfirm xorg-mkfontscale xorg-server xorg-server-common
pacman --needed --noconfirm xorg-server-utils xorg-sessreg xorg-setxkbmap
pacman --needed --noconfirm xorg-smproxy xorg-utils xorg-x11perf
pacman --needed --noconfirm xorg-xauth xorg-xbacklight xorg-xclock
pacman --needed --noconfirm xorg-xcmsdb xorg-xcursorgen xorg-xdpyinfo
pacman --needed --noconfirm xorg-xdriinfo xorg-xev xorg-xgamma
pacman --needed --noconfirm xorg-xhost xorg-xinit xorg-xinput
pacman --needed --noconfirm xorg-xkbcomp xorg-xkbevd xorg-xkbutils
pacman --needed --noconfirm xorg-xkill xorg-xlsatoms xorg-xlsclients
pacman --needed --noconfirm xorg-xmessage xorg-xmodmap xorg-xpr
pacman --needed --noconfirm xorg-xprop xorg-xrandr xorg-xrdb
pacman --needed --noconfirm xorg-xrefresh xorg-xset xorg-xsetroot
pacman --needed --noconfirm xorg-xvinfo xorg-xwd xorg-xwininfo
pacman --needed --noconfirm xorg-xwud xterm xulrunner
pacman --needed --noconfirm zip